# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd6e13d188038bed135be90b6d649d0648c7c281a081f2a2ac3057bc873d8256e5636b6560ac204702ee874190a168cc24eabbb5c28e5bf098445e40d563579d

test:
  secret_key_base: 96d815be0f3e8e4cea501c0ab5688b282dab890e2b03c9f796a5c1b955644a78899b288e2c951011ade86e6035fddfa0c17ff57c745549caa0dbba236976e604

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
